### ISSUE TITLE
AppRegistryNotReady error in django 1.9

### ISSUE THREAD

**Issue by olivier65** [manuelnaranjo/django-database-view#1]
Adding 'dbview' to INSTALLED_APPS causes django to crash on start with an AppRegistryNotReady error. I believe this is due to this restriction (from django 1.9 release notes):

> All models need to be defined inside an installed application or declare an explicit app_label. Furthermore, it isn’t possible to import them before their application is loaded. In particular, it isn’t possible to import models inside the root package of an application.

**Comment by manuelnaranjo** [comment]
@olivier65 I haven't checked django 1.9 yet, when I get sometime I'll try out.

**Comment by moorchegue** [comment]
@olivier65 a bit of a late response… I just ran into the same issue and found that one way to fix that is just not include the 'dbview' in the INSTALLED_APPS. It doesn't look like that does anything at all anyway. Except tripping over the __init__.py imports. Which aren't necessary too, so another way to fix it is to remove those imports and use `from dbview.models import CreateView` instead of the shortcut.

**Comment by moorchegue** [comment]
I ended up doing both, so this shouldn't be a problem anymore.
